name: prodpipeline
on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Commit ID to deploy"
        required: true
        type: string
concurrency:
  group: roboshop-catalogue-prod
  cancel-in-progress: false
permissions:
  contents: read
  security-events: read
  statuses: write
jobs:
  prodpipeline:
    if: github.ref == 'refs/heads/main'
    uses: hemanchandra-devops/workflows/.github/workflows/prodnodejspipeline.yaml@main
    with:
      project: "roboshop"
      component: "catalogue"
      version: ${{ inputs.version }}
    secrets: inherit